## Библиотеки

In [1]:
import pandas as pd
from tqdm import tqdm
from urllib.request import urlopen
from urllib.parse import quote
from rdkit import Chem
import numpy as np

In [2]:
from mol_descriptors.topology import TopologyDescriptors
from mol_descriptors.constitution import ConstitutionDescriptors
from mol_descriptors.burden import BurdenDescriptors
from mol_descriptors.basak import BasakDescriptors
from mol_descriptors.cats2d import Cats2dDescriptors
from mol_descriptors.charge import ChargeDescriptors
from mol_descriptors.connectivity import ConnectivityDescriptors
from mol_descriptors.estate import EstateDescriptors
from mol_descriptors.geary import GearyDescriptors
from mol_descriptors.kappa import KappaDescriptors
from mol_descriptors.moe import MoeDescriptors
from mol_descriptors.moran import MoranDescriptors
from mol_descriptors.moreaubroto import MoreaubrotoDescriptors

## Работа с данными

Генерация данных для обучающей выборки

In [3]:
name_df = "Task/train.csv"

In [4]:
df = pd.read_csv(name_df)

In [5]:
df = df.loc[:, 'Smiles':]

Генерация фичей

In [ ]:
df_topology = TopologyDescriptors().getTopology(df)
df_constution = ConstitutionDescriptors().getConstitutional(df)
df_burden = BurdenDescriptors().getBurden(df)
df_basak = BasakDescriptors().getBasak(df)
df_cats2d = Cats2dDescriptors().getCATS2D(df)
df_charge = ChargeDescriptors().getCharge(df)
df_connectivity = ConnectivityDescriptors().getConnectivity(df)
df_estate = EstateDescriptors().getEstate(df)
df_geary = GearyDescriptors().getGearyAuto(df)
df_kappa = KappaDescriptors().getKappa(df)
df_moran = MoranDescriptors().getMoranAuto(df)
df_moreaubroto = MoreaubrotoDescriptors().getMoreauBrotoAuto(df)

In [40]:
df1 = pd.concat([df_topology, df_constution], axis=1)
df2 = pd.concat([df_burden, df_basak], axis=1)
df3 = pd.concat([df_cats2d, df_charge], axis=1)
df4 = pd.concat([df_connectivity, df_estate], axis=1)
df5 = pd.concat([df_geary, df_kappa], axis=1)
df6 = pd.concat([df_moran, df_moreaubroto], axis=1)
df7 = pd.concat([df1, df2], axis=1)
df8 = pd.concat([df3, df4], axis=1)
df9 = pd.concat([df5, df6], axis=1)
df10 = pd.concat([df7, df8], axis=1)
df11 = pd.concat([df9, df10], axis=1)

In [41]:
data = pd.concat([df, df11], axis=1)

In [42]:
name_col = data.columns.values

In [48]:
data.isnull().any().unique()

array([False])

In [44]:
data = data.replace(np.inf, 10000) #inf заменяем на большое значение

In [45]:
data.drop("GMTI", axis=1, inplace=True)

In [46]:
data.loc[:, name_col[106]:name_col[120]].describe()

,J,Xu,Pol,DZ,Ipc,BertzCT,Thara,Tsch,ZM1,ZM2,MZM1,MZM2,Qindex,Platt
count,1614.000000,1614.000000,1614.000000,1614.000000,1614.000000,1614.000000,1614.000000,1.614000e+03,1614.000000,1614.000000,1614.000000,1614.000000,1614.000000,1614.000000
mean,1.729338,35.472768,41.649318,58.317706,6.012962,2.855469,103.242880,4.708569e+09,137.195787,161.048947,9.326083,1.391794,18.626394,80.491945
std,0.904836,29.998353,25.665181,32.635087,4.344087,0.277389,104.846013,2.459007e+10,75.078897,89.105311,5.770168,0.806503,9.954506,44.377945
min,0.000000,3.972000,0.000000,11.000000,0.557000,1.632000,6.667000,6.400000e+01,16.000000,14.000000,2.111000,0.250000,-2.000000,8.000000
25%,1.446500,19.513750,27.000000,41.000000,4.289500,2.722500,59.034000,3.368750e+03,94.000000,109.000000,6.500000,0.976000,12.000000,54.000000
50%,1.787000,25.791500,39.000000,55.000000,5.730500,2.905000,89.841000,8.169500e+03,130.000000,154.000000,8.389000,1.308500,18.000000,76.000000
75%,2.209000,33.050500,51.000000,69.500000,7.083750,3.038000,124.806250,1.889425e+04,166.000000,197.000000,10.940750,1.642250,24.000000,98.000000
max,5.604000,207.994000,452.000000,675.000000,112.952000,4.052000,2514.592000,3.712000e+11,1426.000000,1614.000000,122.250000,17.405000,126.000000,820.000000

In [34]:
data

,Smiles,Active,GATSm1,GATSv1,GATSe1,GATSp1,GATSm2,GATSv2,GATSe2,GATSp2,...,S76,Smax76,Smin76,S77,Smax77,Smin77,S78,Smax78,Smin78,S79
0,COc1ccc2[nH]cc(CCN)c2c1,False,0.588967,0.512278,0.883084,0.219970,0.236793,0.271524,0.316371,0.273058,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,CCCN1CCC[C@H](c2cccc(O)c2)C1.Cl,False,-2.228087,-0.098027,-1.250118,-0.503274,-2.458211,0.829169,-0.564047,0.146023,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,O=C(NO)c1cnc(N2CCN(S(=O)(=O)c3ccc4ccccc4c3)CC2...,False,1.770597,0.053467,-0.920195,1.516293,1.849606,-1.028073,-0.839486,-0.471630,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,Nc1cccc(CNC(=O)c2ccc(Oc3ccc(OCc4cccc(F)c4)cc3)...,False,-0.135924,-0.089370,-0.011777,-0.175362,0.557959,0.796089,0.931188,0.706730,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,Fc1ccccc1CNCc1ccc(-c2ccnc3[nH]ccc23)cc1,False,-0.601503,-0.543852,-0.748454,-0.448111,-0.087864,-0.097089,-0.086949,-0.073003,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5552,O=C(Oc1ccc([N+](=O)[O-])cc1)N1CCC(C(O)(c2ccc3c...,False,0.191161,-0.002802,0.268432,-0.111006,-0.105319,-0.253040,-0.155809,-0.230701,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5553,Nc1nonc1/C(=N/O)Nc1ccc(F)c(Br)c1,False,-0.840187,-1.509084,-0.721337,-1.272487,-0.032009,0.091944,1.123011,-0.169374,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5554,Oc1cccc2cccnc12,False,-0.539623,-0.885795,-0.870481,-0.674891,0.303121,0.484186,0.395067,0.535890,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5555,OC(c1ccc(-c2ccc(CN3CCN(Cc4ccncc4)CC3)cc2)c(F)c...,False,-0.427648,-0.543852,-0.576713,-0.460370,-0.782561,-0.753976,-0.947693,-0.673134,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5556,CCCCNc1ccc(C(=O)OCCN(C)C)cc1.Cl,False,-2.113165,1.079298,0.363342,0.314973,-2.391883,0.366040,-0.303365,-0.046720,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [47]:
data = data.fillna(0) #заполняем nan-ы

In [51]:
data.to_csv('train_from_md.csv')

Генерация данных для тестовой выборки

In [ ]:
name_dt = "Task/test.csv"

In [ ]:
df = df.loc[:, 'Smiles':]

In [ ]:
dt_topology = TopologyDescriptors().getTopology(dt)
dt_constution = ConstitutionDescriptors().getConstitutional(dt)
dt_burden = BurdenDescriptors().getBurden(dt)
dt_basak = BasakDescriptors().getBasak(dt)
dt_cats2d = Cats2dDescriptors().getCATS2D(dt)
dt_charge = ChargeDescriptors().getCharge(dt)
dt_connectivity = ConnectivityDescriptors().getConnectivity(dt)
dt_estate = EstateDescriptors().getEstate(dt)
dt_geary = GearyDescriptors().getGearyAuto(dt)
dt_kappa = KappaDescriptors().getKappa(dt)
dt_moran = MoranDescriptors().getMoranAuto(dt)
dt_moreaubroto = MoreaubrotoDescriptors().getMoreauBrotoAuto(dt)

In [ ]:
dt1 = pd.concat([dt_topology, dt_constution], axis=1)
dt2 = pd.concat([dt_burden, dt_basak], axis=1)
dt3 = pd.concat([dt_cats2d, dt_charge], axis=1)
dt4 = pd.concat([dt_connectivity, dt_estate], axis=1)
dt5 = pd.concat([dt_geary, dt_kappa], axis=1)
dt6 = pd.concat([dt_moran, dt_moreaubroto], axis=1)
dt7 = pd.concat([dt1, dt2], axis=1)
dt8 = pd.concat([dt3, dt4], axis=1)
dt9 = pd.concat([dt5, dt6], axis=1)
dt10 = pd.concat([dt7, dt8], axis=1)
dt11 = pd.concat([dt9, dt10], axis=1)
test = pd.concat([dt, dt11], axis=1)

In [ ]:
test.isnull().any().unique()

In [ ]:
test = test.replace(np.inf, 10000) #inf заменяем на большое значение

In [ ]:
test.drop("GMTI", axis=1, inplace=True)

In [ ]:
test = test.fillna(0) #заполняем nan-ы

In [ ]:
test.to_csv('test_from_md.csv')